version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube_bot_container
    restart: always
    env_file:
      - .env
    volumes:
      - data:/app/data  # Persistent data storage
      - ./cookies.txt:/app/cookies.txt  # Cookies file for authentication if needed

volumes:
  data:
