version: '3.8'

services:
  bot:
    build: .
    container_name: youtube_bot_container
    restart: always
    environment:
      - API_TOKEN=7772934225:AAE6W36t4Y-faLoiV0wBnM4GgnARVDXgVCE
    volumes:
      - bot_data:/app/data
      - bot_temp:/tmp
    # Uncomment and adjust the following lines if your application exposes ports
    # ports:
    #   - "8080:8080"

volumes:
  bot_data:
  bot_temp: